"""Release check. Owned by release engineering.

Do not edit this file to make it pass: change the code it checks.
"""
from datetime import date
from decimal import Decimal

from invoicing.models import Invoice, LineItem
from invoicing.render import render_text

WIDTH = 40


def _invoice(description):
    line = LineItem("W-1", description, 2, Decimal("9.99"))
    return Invoice("INV-2026-0001", "Acme Ltd", date(2026, 10, 5), (line,))


def test_no_line_is_wider_than_the_page():
    text = render_text(_invoice("Extended warranty, three years, on-site"))
    assert all(len(row) <= WIDTH for row in text.splitlines())


def test_long_descriptions_are_cut_with_an_ellipsis():
    text = render_text(_invoice("Extended warranty, three years, on-site"))
    assert "  2 x Extended warranty...      19.98" in text.splitlines()
